"""Integracion de mapas

Revision ID: 6100d87392d3
Revises: b531827e5b96
Create Date: 2025-07-23 20:05:18.126485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6100d87392d3'
down_revision = 'b531827e5b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpx_file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kml_file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kmz_file_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.drop_column('kmz_file_url')
        batch_op.drop_column('kml_file_url')
        batch_op.drop_column('gpx_file_url')

    # ### end Alembic commands ###
