"""empty message

Revision ID: f81dcb32bcc1
Revises: 97f4ee006703
Create Date: 2025-07-23 00:56:18.534723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81dcb32bcc1'
down_revision = '97f4ee006703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_travel', schema=None) as batch_op:
        batch_op.alter_column('hora_salida_ida',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_llegada_ida',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_vuelta',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_llegada_vuelta',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_escala',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_llegada_escala',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('international_travel', schema=None) as batch_op:
        batch_op.alter_column('hora_llegada_escala',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_escala',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('hora_llegada_vuelta',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_vuelta',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('hora_llegada_ida',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_ida',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
